package_assets:         on                    # (on, off, always)
embed_assets:           on                    # (on, off, datauri)
compress_assets:        on                    # (on, off)
gzip_assets:            on                    # (on, off)
template_function:      _.template            # (defaults to the built-in micro-templating)
package_path:           .                     # (defaults to assets)
javascript_compressor:  closure               # (yui, closure)

javascripts:
  soysauce.min:
      - bower_components/fastclick/lib/fastclick.js
      - assets/javascript/hammer.js
      - assets/javascript/legacy-support.js
      - assets/javascript/images-loaded.js
      - assets/javascript/soysauce/core.js
      - assets/javascript/soysauce/utilities/*.js
      - assets/javascript/soysauce/widgets/*.js
